version = "2"

[linters]
default = "fast"
enable = ["revive"]
[linters.settings.revive]
enable-default-rules = true
[linters.settings.depguard.rules.prevent_unmaintained_packages]
list-mode = "lax"
files = ["$all"]
allow = ["$gostd"]

[formatters]
enable = ["gofumpt"]
