[commit-msg]
jobs = [{ name = "commitlint", run = "commitlint lint --message {1}" }]

[pre-commit]
jobs = [
  { name = "lint", run = "mise run lint" },
  { name = "format-check", run = "mise run format-check" },
]

[pre-push]
jobs = [
  { name = "lint", run = "mise run lint" },
  { name = "format-check", run = "mise run format-check" },
  { name = "test", run = "mise run test" },
]

[post-checkout]
jobs = [
  { name = "tidy mise", run = "mise install -q" },
  { name = "tidy go", run = "go mod tidy" },
]

[post-merge]
jobs = [
  { name = "tidy mise", run = "mise install -q" },
  { name = "tidy go", run = "go mod tidy" },
]
