[tools]
go = "latest"
golangci-lint = "latest"
lefthook = "latest"
"go:github.com/conventionalcommit/commitlint" = "latest"


[tasks]
setup = { run = ["mise trust", "mise install", "lefthook install"] }
dev = { run = "go run ./cmd/{{arg(i=0)}}" }
lint = { run = "golangci-lint run --default=standard" }
format = { run = "golangci-lint fmt" }
test = { run = "go test ./..." }
build = { run = "for dir in ./cmd/*/; do go build -o ./bin/$(basename $dir) $dir; done" }
