[tools]
golangci-lint = "2.12.2"
go = "1.26.5"
gofumpt = "0.10.0"
lefthook = "2.1.10"
"github:cocogitto/cocogitto" = { version = "7.0.0" }

[settings]
disable_backends = ["asdf"]
use_versions_host = false
go.set_gobin = false
